/*
 * This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.neatmonster.nocheatplus.checks.moving.velocity;

/**
 * Flags for use with velocity entries. There may be flags specific to certain
 * types of velocity entries only, these may get prefixed somehow some day.
 * 
 * @author asofold
 *
 */
public class VelocityFlags {
    
    private static long f_next = 1;
    private static long f_flag() {
        final long flag;
        synchronized(VelocityFlags.class) {
            if (f_next <= 0L) {
                throw new IllegalStateException("No more flags available.");
            }
            flag = f_next;
            f_next *= 2L;
        }
        return flag;
    }

    /** Create new entries with an actActCount increased by one. */
    public static final long SPLIT_RETAIN_ACTCOUNT = f_flag();

    /**
     * Create a new entry if the used amount leaves at least a third of the set
     * amount. Entries generated by splitting are prepended by default.
     */
    public static final long SPLIT_ABOVE_THIRD = f_flag();

    /**
     * Create a new entry if the used amount leaves at least an amount of 0.42.
     * Entries generated by splitting are prepended by default.
     */
    public static final long SPLIT_ABOVE_0_42 = f_flag();

    /**
     * Entries with this flag originate from moving blocks (typically pistons).
     */
    public static final long ORIGIN_BLOCK_MOVE = f_flag();

    /**
     * Entries with this flag originate from bouncing off blocks (typically
     * slime blocks).
     */
    public static final long ORIGIN_BLOCK_BOUNCE = f_flag();

    /**
     * Entries with this flag originate from pvp (likely faked, due to the
     * server not sending properly).
     */
    public static final long ORIGIN_PVP = f_flag();
    
    /**
     * Meta flag: entries with this flag are for internal purposes (always faked) and should therefore be ignored by velocity checks.
     */
    public static final long FAKED = f_flag();
    
    /**
     * Entries with this flag are assumed to have originated from an explosion. 
     */
    public static final long ORIGIN_EXPLOSION = f_flag();
    
    /**
     * Meta flag: this velocity is applied as an addition to the player's current motion, rather than replacing it like other types.
     */
    public static final long ADDITIVE = f_flag();
}
